// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://yourdomain.com/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://yourdomain.com/support",
            "email": "support@yourdomain.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Login using username and password, and return a JWT token for authorized access",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Login and generate JWT token",
                "parameters": [
                    {
                        "description": "Login request with username and password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.JWTResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "Object"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Setup routes for administrative resources like users, servers, employees, etc.",
                "tags": [
                    "admin"
                ],
                "summary": "Setup admin routes",
                "responses": {}
            }
        },
        "/{resource}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Setup routes for CRUD operations on resources like users, servers, employees, etc.",
                "tags": [
                    "user"
                ],
                "summary": "Setup GET resource routes",
                "parameters": [
                    {
                        "enum": [
                            "example1",
                            "example2",
                            "exampleRelational"
                        ],
                        "type": "string",
                        "description": "Resource type",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Setup routes for administrative resources like users, servers, employees, etc.",
                "tags": [
                    "admin"
                ],
                "summary": "Setup admin routes",
                "parameters": [
                    {
                        "enum": [
                            "user",
                            "example1",
                            "example2",
                            "exampleRelational"
                        ],
                        "type": "string",
                        "description": "Resource type",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON request body for POST and PATCH operations",
                        "name": "defaultRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DefaultRequest"
                        }
                    },
                    {
                        "description": "Example1 object to create",
                        "name": "example1",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.Example1"
                        }
                    },
                    {
                        "description": "Example2 object to create",
                        "name": "example2",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.Example2"
                        }
                    }
                ],
                "responses": {}
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Setup routes for administrative resources like users, servers, employees, etc.",
                "tags": [
                    "admin"
                ],
                "summary": "Setup admin routes",
                "parameters": [
                    {
                        "enum": [
                            "user",
                            "example1",
                            "example2",
                            "exampleRelational"
                        ],
                        "type": "string",
                        "description": "Resource type",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON request body for POST and PATCH operations",
                        "name": "defaultRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DefaultRequest"
                        }
                    },
                    {
                        "description": "Example1 object to create",
                        "name": "example1",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.Example1"
                        }
                    },
                    {
                        "description": "Example2 object to create",
                        "name": "example2",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.Example2"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/{resource}/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Setup routes for CRUD operations on resources like users, servers, employees, etc.",
                "tags": [
                    "user"
                ],
                "summary": "Setup GET resource routes",
                "parameters": [
                    {
                        "enum": [
                            "example1",
                            "example2",
                            "exampleRelational"
                        ],
                        "type": "string",
                        "description": "Resource type",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource ID (for operations on specific resources)",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Setup routes for administrative resources like users, servers, employees, etc.",
                "tags": [
                    "admin"
                ],
                "summary": "Setup admin routes",
                "parameters": [
                    {
                        "enum": [
                            "user",
                            "example1",
                            "example2",
                            "exampleRelational"
                        ],
                        "type": "string",
                        "description": "Resource type",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource ID (for operations on specific resources)",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {}
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Setup routes for administrative resources like users, servers, employees, etc.",
                "tags": [
                    "admin"
                ],
                "summary": "Setup admin routes",
                "parameters": [
                    {
                        "enum": [
                            "user",
                            "example1",
                            "example2",
                            "exampleRelational"
                        ],
                        "type": "string",
                        "description": "Resource type",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource ID (for operations on specific resources)",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "description": "JSON request body for POST and PATCH operations",
                        "name": "defaultRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DefaultRequest"
                        }
                    },
                    {
                        "description": "Example1 object to create",
                        "name": "example1",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.Example1"
                        }
                    },
                    {
                        "description": "Example2 object to create",
                        "name": "example2",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.Example2"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "models.DefaultRequest": {
            "type": "object",
            "properties": {
                "field": {
                    "description": "Field is a placeholder for data that might be required in some requests.",
                    "type": "string"
                }
            }
        },
        "models.Example1": {
            "type": "object",
            "properties": {
                "field1": {
                    "description": "Field1 is the primary key of the Example1 table.",
                    "type": "string"
                },
                "field2": {
                    "description": "Field2 stores additional data related to Example1.",
                    "type": "string"
                }
            }
        },
        "models.Example2": {
            "type": "object",
            "properties": {
                "field1": {
                    "type": "string"
                },
                "field2": {
                    "type": "string"
                }
            }
        },
        "models.JWTResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "Token is the JWT token assigned to the authenticated user.",
                    "type": "string"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "Password is the user's password used for authentication.",
                    "type": "string"
                },
                "username": {
                    "description": "Username is the unique identifier for the user attempting to log in.",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "JWT to login",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "security": [
        {
            "ApiKeyAuth": []
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Admin API Documentation",
	Description:      "This is a sample API for managing administrative resources like users, servers, employees, groups, etc.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
