name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.6]  # Assuming you wish to use this exact version, please confirm if it exits.
        os: [windows, linux, darwin]
        arch: [amd64, arm64] #  386, arm not supported by darwin

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build binary
      run: |
        if [ "${{ matrix.os }}" = "windows" ]; then
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o "${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }}.exe"
        else
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o "${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }}"
        fi

    - name: List files
      run: ls -l

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
        path: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
        if-no-files-found: error

  publish_release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
      actions: read
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: true
        prerelease: false

    - name: Upload release assets
      uses: dwenegar/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
        assets_path: .
